#!/usr/bin/env bash
# the script enables a server to run and listen
# on port 80 of all servers active IPv4 IPs

sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
