#!/usr/bin/env bash
# the script enables a server to run and listen
# on port 80 of all servers active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
