#!/usr/bin/env bash
# script displays Best School 10 times.

COUNTER=1
while [ "$COUNTER" -le 10 ]
do
    if [ "$COUNTER" -eq 9 ]
    then
	    echo "Best School"
	    echo "Hi"
    else
	    echo "Best School"
    fi
    COUNTER=$(( COUNTER + 1 ))
done
